language: python
python:
  - "3.6"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
# command to run tests
script:
  - "python -m unittest api/tests/test_api.py"
  - "coverage run -m unittest discover -s api/tests/"
after_success: coveralls