language: python
python:
  - "3.6"
# command to install dependencies
install:
  - "pip install -r backend/requirements.txt"
# command to run tests
script:
  - "python -m unittest discover -s backend/api/tests/"
  - "coverage run -m unittest discover -s backend/api/tests/"
  - "coverage xml"
  - "python-codacy-coverage -r coverage.xml"
after_success: coveralls
notifications:
  slack: andela:czTH1K9R39l0e6MwUUi4RnFc