swagger: '2.0'
info:
  title: Bucket list API
  version: "0.1.0"
  description: The api specification document to the online bucket list management system
  contact:
    email: edwin.kato@andela.com
basePath: "/v1"
consumes:
  - application/json
produces:
  - application/json
security:
  # enable OAuth protection for all REST endpoints
  # (only active if the TOKENINFO_URL environment variable is set)
  - oauth2: [uid]
